# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chess_pb2 as chess__pb2


class ChessServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeMove = channel.unary_unary(
                '/chess.standard.ChessService/MakeMove',
                request_serializer=chess__pb2.Move.SerializeToString,
                response_deserializer=chess__pb2.MoveResultMessage.FromString,
                )
        self.EndGame = channel.unary_unary(
                '/chess.standard.ChessService/EndGame',
                request_serializer=chess__pb2.GameOverMessage.SerializeToString,
                response_deserializer=chess__pb2.MoveResultMessage.FromString,
                )


class ChessServiceServicer(object):
    """Service definition
    """

    def MakeMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeMove': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeMove,
                    request_deserializer=chess__pb2.Move.FromString,
                    response_serializer=chess__pb2.MoveResultMessage.SerializeToString,
            ),
            'EndGame': grpc.unary_unary_rpc_method_handler(
                    servicer.EndGame,
                    request_deserializer=chess__pb2.GameOverMessage.FromString,
                    response_serializer=chess__pb2.MoveResultMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chess.standard.ChessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChessService(object):
    """Service definition
    """

    @staticmethod
    def MakeMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chess.standard.ChessService/MakeMove',
            chess__pb2.Move.SerializeToString,
            chess__pb2.MoveResultMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EndGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chess.standard.ChessService/EndGame',
            chess__pb2.GameOverMessage.SerializeToString,
            chess__pb2.MoveResultMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
