name: Python package

on:
  push:
    branches: ['*']
  pull_request:
    branches:
      - 'main'
      - 'development'

jobs:
  Run pytest -v:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        # install your project's dependencies here
    - name: Run tests with pytest
      run: |
        pytest -v
